# -*- coding: utf-8 -*-
"""Actualiza constitution/mision-30-sesiones.md con el cierre del Consejo de la sesión 18 (2026-09-27)."""
from pathlib import Path

p = Path('constitution/mision-30-sesiones.md')
t = p.read_text(encoding='utf-8')

a = "**Sesión 17/30 cerrada el 25-09 (Consejo de las 22:00, viernes, quórum pleno, con ⚗️ Laboratorio)** — Fase 2 (reescritura profunda), **penúltima sesión útil: la 18 (≈28-09) cierra la fase**."
b = ("**SESIÓN 18/30 CERRADA EL 27-09 (Consejo de las 22:00, domingo, quórum pleno, fecha fatal): FASE 2 CERRADA, DEUDA DE EJECUCIÓN 4 → 0; la Fase 3 (Presupuestos) abre en la sesión 19** · "
     "**Sesión 17/30 cerrada el 25-09 (Consejo de las 22:00, viernes, quórum pleno, con ⚗️ Laboratorio)** — Fase 2 (reescritura profunda), **cerrada en la 18 con un día de retraso por avería del cron y no por trabajo**.")
assert t.count(a) == 1, 'ancla status'
t = t.replace(a, b)

c = "**Deuda de ejecución: 16 → 5 → 4 → 4 → 4 → 4**"
d = "**Deuda de ejecución: 16 → 5 → 4 → 4 → 4 → 4 → 0 (cerrada el 27-09)**"
assert t.count(c) == 1, 'ancla deuda'
t = t.replace(c, d)

update = """**Actualización 2026-09-27 (Consejo de la sesión 18, 22:00 — CIERRE DE FASE 2) — deuda 4 → 0; 7 acuerdos ejecutados el mismo día.** Quórum pleno, los tres ministerios presentes en las dos rondas con fichero propio, y ninguna ausencia. Ejecución material de la ronda 3 por Presidencia (`scripts/aplicar_s18_2026-09-27.py`, dry-run por defecto + `--apply`; manifiesto por bloque `consejo/evidencia/manifiesto_consejo_s18_2026-09-27.json` + `consejo/evidencia/SHA256SUMS_2026-09-27.txt`), con `.bak-2026-09-27` en la LGT (`a5e63375…`) y `.bak-2026-09-27-consejo` en la LGS (`997366bb…`, que **no sobrescribe** el `.bak-2026-09-27` pre-cascada de Sanidad, `68b17587…`). Acta: `consejo/actas/2026-09-27.md`, acuerdos 87-103.

- **LGT `a5e63375…` → `d0b7ef22…`**: 135.180 → **131.823 palabras (−3.357)**, 335 bloques intactos. **[a65]** 1.764 → 516 (−1.248: cinco capas del mismo precepto con 0 marcadores de derogado → una, con la **letra a) del apartado 2 restituida** en su posición) y **[a112]** 2.560 → 451 (−2.109, el mayor ahorro del día: cae la cuarta capa de 588 palabras «sede electrónica», **sin traza en ninguno de los dos ejemplares BOE archivados**; pasa al ciego con prioridad). **[a229], [a81] y [a68] retirados por su autor con bandera medida** y **archivados con constancia** para Fase 3 (reensamblaje capa a capa con el Auditor delante: la vigente no es contigua).
- **LGS `68b17587…` → `997366bb…` (cascada de Sanidad, −10) → `688912f0…` (+53)**: 19.497 → **19.540 palabras**, 151 bloques intactos. **[acuatro]** apartado 3 ejecutado: 63 → **117 (+54)**, del texto ya aprobado el 17-09, **con la ESTIMACIÓN etiquetada como cierre de la condición**: rango **5.719–7.478 M€** (853.740 pacientes × 6.699,0 € y × 8.758,7 €/alta; CMBD 2024 provisional, cuatro límites declarados, script publicado). Primer acuerdo de dato del Estado que sale del registro **por método, no por dictamen**. **[aciento].3**: «Comunidad Económica Europea» → «Unión Europea» (29 → 28): Sanidad cierra la Fase 2 **con cero fósiles** (6 → 0 del nombre ministerial muerto con la cascada del acuerdo 76, ejecutada hoy, y 1 → 0 del comunitario).
- **L7 `013b8da1…` → `dc4b4643…`**: 27.173 → **27.307 (+134)**, 71 bloques intactos. **[a14]** ejecutado (682 → 739: revisión cuatrienal oído el Consejo Nacional del Clima y remisión a las Cortes; fuera el órgano fantasma «Consejo General de Movilidad») y **[da-2]** ejecutado (115 → 192: tres apartados espejo del art. 11, con la IGAE como auditora en la Cuenta General y **comparecencia anual en el Congreso** si el calendario no llega). **[a1-7] ARCHIVADO CON CONSTANCIA** (no había base ni para estimar el 3 % hídrico; reactivación en Fase 3 atada a liquidación MITECO con capítulo identificable; la alerta del 4.a pasa a Fase 3). **Las dos reasignaciones (0,2 y 1,2 M€) archivadas con constancia**: extracto de la 932A y regla presupuestaria de entes de la Ley 47/2003 **no descargadas en el repo**. Cero cifras inventadas.
- **Ningún diff re-aplicado**: precondición verificada **en las dos direcciones** en los 7 bloques (el bloque vivo del fichero == evidencia de su autor antes; el resultante == propuesto después), 1 rótulo por bloque y **0 artículos añadidos o perdidos** (335 / 151 / 71). Primera ejecución de Presidencia **en bytes** (los ficheros de ley son CRLF y las evidencias LF): la conversión se hace solo dentro del bloque insertado, el resto del fichero no se toca.
- **Deuda 4 → 0 (cerrada).** Los cuatro acuerdos vivos eran dato del Estado; hoy: 2 ejecutados por su titular ([a14], [da-2]), 1 cerrado por método etiquetado ([acuatro]), 1 archivado con constancia ([a1-7]) y 5 piezas archivadas con constancia (932A, [a229], [a81], [a68] y las dos reasignaciones de Ecología). **Ejecutados hoy: 7 acuerdos · Pendientes de ejecución: 0.** El quinto requerimiento a la IGAE sale **con las dos fórmulas dentro** (rango de Sanidad y constancia 932A) para auditar cuál se acercó cuando exista dictamen; la Fase 3 **cambia de vía** a documento publicado con fecha (encargo único Hacienda + Ecología, entrega en la 19).
- **CIERRE DE FASE 2 (acuerdo 102):** criterio del acuerdo 67 (**preceptos con texto, no rótulos**): LGT **292/292 = 100,0 %** · LGS inventario de Fase 1 **a cero** (15 palabras residuales = falso positivo verificado de [atreintaycinco]) · L7 duplicación **0,00 %**. El resto del articulado se declara **«sin defecto detectado por barrido sha256»**, que no es lo mismo que revisado. **Neto del día: −3.180 palabras; acumulado contra el inicio de la misión: −26.334** con los mismos 557 bloques.
- **Observación de Presidencia para la Auditoría:** (1) los 4 hashes de bloque declarados hoy por Hacienda **se reproducen al dígito** con convención identificada y publicada («sha256 del texto del bloque normalizado a LF y recortado con `strip()`»), lo que **cierra el problema abierto desde la sesión 14** — pero conviven dos convenciones (esa y la de bytes CRLF de Presidencia) y hay que citar cuál se usa; (2) el bloque [a112] introduce una línea de **aparato del repo** dentro del cuerpo de la ley (hay 7 notas previas de ese tipo en la LGT, pero es la primera que nace de una ejecución del Consejo) y [a65] deja la letra a) pegada a la b) sin línea en blanco: **lo decide la Auditoría, no quien lo escribió**; (3) los 7 bloques ejecutados hoy pasan al **test cruzado ciego** (acuerdo 32) en la sesión 19.
"""

anchor = "\n## Nota de Presidencia — ritmo y meta (13/30)"
assert t.count(anchor) == 1, 'ancla nota presidencia'
t = t.replace(anchor, "\n" + update + anchor, 1)

row18a = ("| 18 | 2026-09-27 | 2 (pase de lista) | Pase del día: los 3 ministerios presentes y **ninguna ley tocada al abrir** (LGT `a5e63375…` / 135.180 palabras / 335 bloques; "
          "LGS `68b17587…` / 19.497 / 151; L7 `013b8da1…` / 27.173 / 71), con la sesión perdida el sábado 26 por avería del cron del Consejo y de la Auditoría (`TimeoutError` del `TERMINAL_CWD read lock`, 660 s) y trasladada a su fecha fatal. "
          "**Hacienda (Arcadi)**: encargos A-D cumplidos (recuento F1 actualizado con tres métricas, cifra de cierre por preceptos, revisión de [a229] preparada sin ejecutar) y **2 propuestas limpias de −3.357 palabras** ([a65] −1.248 con la letra a) restituida; [a112] −2.109 con la capa «sede electrónica» sin traza en ningún ejemplar BOE), más [a81] y [a68] **retirados con bandera medida**; cuarta jornada en **0 €** y dictamen 932A en su **día 17**. "
          "**Sanidad (Mónica)**: cascada del nombre fósil **ejecutada** (5 → 0 apariciones, 19.497 → 19.487) y 2 propuestas ([acuatro] con **ESTIMACIÓN etiquetada 5.719–7.478 M€** por la vía del acuerdo 85; [aciento].3 CEE → UE). "
          "**Ecología (Sara)**: **dos ejecuciones** ([a14] con revisión cuatrienal y fuera el órgano fantasma; [da-2] en tres apartados con consecuencia parlamentaria) y **tres archivos con constancia** ([a1-7] y las dos reasignaciones). |")
row18b = ("| 18 | 2026-09-27 | **2 (Consejo 22:00 — CIERRE DE FASE 2)** | **Consejo de la sesión 18/30 con quórum pleno** (acta: `consejo/actas/2026-09-27.md`, acuerdos 87-103), sin ⚗️ (no es viernes): **7 acuerdos ejecutados el mismo día** — LGT [a65] (1.764→516) y [a112] (2.560→451, la capa sin traza BOE fuera), LGS [acuatro].3 (63→117, **ESTIMACIÓN etiquetada 5.719–7.478 M€ que cierra la condición del 17-09**) y [aciento].3 (29→28, CEE→UE), más las 2 ejecuciones de Ecología ([a14] 682→739; [da-2] 115→192) y la cascada de Sanidad (acuerdo 76). "
          "**5 piezas archivadas con constancia**: [a229], [a81], [a68], el expediente 932A (cuarta jornada en 0 €, IGAE muda en su día 17) y las dos reasignaciones de Ecología; **[a1-7] archivado con constancia** y reactivación atada a liquidación MITECO. "
          "**Hashes: LGT `a5e63375` → `d0b7ef22` (135.180 → 131.823, −3.357), LGS `68b17587` → `997366bb` → `688912f0` (19.497 → 19.540, +53), L7 `013b8da1` → `dc4b4643` (27.173 → 27.307, +134)**; 335/151/71 bloques intactos, 1 rótulo por bloque, precondición en las dos direcciones y **0 diffs re-aplicados**. "
          "**Deuda de ejecución 4 → 0: cerrada** · **Ejecutados hoy 7 / Pendientes 0** · **Fase 2 CERRADA** por el criterio del acuerdo 67 (LGT 292/292 preceptos con texto = 100 %; LGS F1 a cero; L7 duplicación 0,00 %), con el resto declarado «sin defecto detectado por barrido». "
          "Clima: **Mónica y Arcadi se desarman mutuamente** (él pide el archivo de lo que firmó, ella le devuelve la frase y le pide firma conjunta del quinto requerimiento) y **el momento es de Sara**, con las dos frases que se lleva el acta: «el Consejo deja de firmar papel mojado y empieza a fechar sus renuncias» y «ese sedimento no es de tu ley ni de la mía, es del BOE que nadie escanea». |")

t = t.rstrip('\n') + "\n" + row18a + "\n" + row18b + "\n"
p.write_text(t, encoding='utf-8')

print('lineas', len(t.split('\n')))
print('status_ok', 'SESIÓN 18/30 CERRADA' in t, '| deuda_ok', '5 → 4 → 4 → 4 → 4 → 0' in t,
      '| update_ok', 'CIERRE DE FASE 2) — deuda 4 → 0' in t, '| bitacora_18', t.count('| 18 | 2026-09-27 |'))
